################################################################################
# $Source: Makefile$
# $Revision: Version 1.0 $
# $Author: Carlos Martinez $
# $Date: 2022-02-23 $
################################################################################
# DESCRIPTION :                                                                                                     
# Makefile
#    Compilation BSW
################################################################################
MALDIR  = ./MCAL
HALDIR  = ./HAL
SERDIR  = ./Services

bsw:
	@echo
	@echo "Executing BSW Makefile"
	@echo
	@$(MAKE) -C $(MALDIR)
	@echo
	@$(MAKE) -C $(HALDIR)
	@echo
	@$(MAKE) -C $(SERDIR)
	@echo
################################################################################
 #|    ID   | JIRA Ticket |     Date    |            Description               |
 #| carlosm |     NA      | 23-Feb-2022 | First version of Makefile            |
################################################################################
